# 数据集的根目录
path: ./

# 训练、验证和测试集的图像路径
train: train
val: valid
test: test

# 类别数量
nc: 21

# 类别名称列表
names: ['apple', 'banana', 'orange', 'broccoli', 'carrot', 'tomato', 'grape', 'watermelon', 'pineapple', 'strawberry', 'lettuce', 'potato', 'onion', 'cucumber', 'bell pepper', 'cherry', 'peach', 'pear', 'plum', 'kiwi', 'mango']